apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - export-image-ref-task.yaml
  - fetch-source-task.yaml
  - git-clone-task.yaml
  - git-source-template.yaml
  - kaniko-git-pipeline.yaml
  - kaniko-image-template.yaml
  - kaniko-pipeline.yaml
  - kaniko-task.yaml
  - network-policies.yaml
  - ns.yaml
  - sa.yaml
  - simple-supply-chain.yaml
  - trivy-image-template.yaml
  - trivy-pipeline.yaml
  - trivy-task.yaml
