---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  namespace: cartographer-build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build
  namespace: cartographer-build
rules:
  - apiGroups: [source.toolkit.fluxcd.io]
    resources: [gitrepositories]
    verbs: ["*"]
  - apiGroups: [carto.run]
    resources: [runnables]
    verbs: ["*"]
  - apiGroups: [tekton.dev]
    resources: [pipelineruns]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build
  namespace: cartographer-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build
subjects:
  - kind: ServiceAccount
    name: build
    namespace: cartographer-build
