---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    name: registry
    netic.dk/monitoring: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: registry
spec:
  ports:
  - port: 5000
    name: http
    targetPort: http
  clusterIP: None
  selector:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: registry
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
      app.kubernetes.io/instance: registry
  serviceName: "registry"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
        app.kubernetes.io/instance: registry
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: http
